# Generated by Django 4.2.3 on 2023-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="sentiment",
            field=models.CharField(default="Neutral", max_length=200),
        ),
    ]
